name: Store readme in Drive
on:
  push: { branches: [main] }
jobs:
  buildAndTestForSomePlatforms:
    name: Upload readme to drive
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Upload to Drive
      - name: Upload README.md to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: README.md
          credentials: ${{secrets.GSA_CREDS_BASE64}}
          folder: DRIVE_FOLDER_ID